name = "silver-gogo-silverster"
main = "functions/send-telegram.js"

[build]
  command = "npm install"
  cwd = "."

[env.production]
  account_id = "f16914f22a06b7c3ed9eaf8f19e47e3f"
  project_name = "daftar-sv388"
  worker = "submit"

[pages]
  project = "daftar-sv388"
  production = true
  build = {
    output = "public"
  }
