name = "silver-gogo-silverster"
type = "javascript"

[build]
  command = "npm install"

[env.production]
  workers_dev = true
  route = "https://svenus38.com/api/*"
  account_id = "f16914f22a06b7c3ed9eaf8f19e47e3f"
  workers_api = true