name = "silver-gogo-silverster"
type = "javascript"

pages_build_output_dir = "dist"

[build]
  command = "npm run build" 

[env.production]
  workers_dev = true
  route = "https://svenus38.com/api/*"
  account_id = "f16914f22a06b7c3ed9eaf8f19e47e3f"