name = "my-worker"
type = "javascript"
account_id = "f16914f22a06b7c3ed9eaf8f19e47e3f"
zone_id = "b143004292720f2fa1c7d79b214ecb70"
workers_dev = true

[env.production]
workers_dev = false
route = "https://silver-gogo-silverster.pages.dev/submit"